name: Sync GraminCN To Strava

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - strava_sync
    paths:
      - scripts/garmin_to_strava_sync.py
      - requirements.txt

env:
  # please change to your own config.

  RUN_TYPE: garmin_to_strava_cn # support strava/nike/garmin/garmin_cn/keep/only_gpx/nike_to_strava/strava_to_garmin/strava_to_garmin_cn/garmin_to_strava/garmin_to_strava_cn, Please change the 'pass' it to your own
  ATHLETE: Echo
  TITLE: Echo's Running
  MIN_GRID_DISTANCE: 15 # change min distance here
  TITLE_GRID: Over 15km Runs # also here
  GITHUB_NAME: donghao526
  GITHUB_EMAIL: donghao526@gmail.com


  # IGNORE_BEFORE_SAVING: True # if you want to ignore some data before saving, set this to True
  IGNORE_START_END_RANGE: 10 # Unit meter
  # Dont making this huge, just picking points you needing. https://developers.google.com/maps/documentation/utilities/polylineutility using this tool to making your polyline
  IGNORE_POLYLINE: "ktjrFoemeU~IorGq}DeB"
  IGNORE_RANGE: 10 # Unit meter
  SAVE_DATA_IN_GITHUB_CACHE: true # if you deploy in the vercal, check the README
  DATA_CACHE_PREFIX: "track_data_syncstrava1"
  BUILD_GH_PAGES: true # If you do not need GitHub Page please set it to `false`


jobs:
  sync:
    name: Sync
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'strava_sync'
      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Cache Data Files
        if: env.SAVE_DATA_IN_GITHUB_CACHE == 'true'
        uses: actions/cache@v3
        with:
          path: |
            activities
            assets
            TCX_OUT
            FIT_OUT
            Workouts
            run_page/data.db
            src/static/activities.json
            imported.json
          key: ${{ env.DATA_CACHE_PREFIX }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.DATA_CACHE_PREFIX }}-${{ github.sha }}-
            ${{ env.DATA_CACHE_PREFIX }}-

      - name: Run sync Garmin-cn to Strava(Run with Garmin data backup in Strava)
        if: env.RUN_TYPE == 'garmin_to_strava_cn'
        run: |
          python run_page/garmin_sync.py ${{ secrets.GARMIN_SECRET_STRING_CN }} --is-cn
